#ifndef DIALOGTYPEENUM_HPP
#define DIALOGTYPEENUM_HPP

enum DialogType{
  QUESTION_DIALOG,
  YES_NO_QUESTION,
  CHANGE_PASSWORD,
  BOOK_PANEL,
  ADD_COMMENT,
  CHECK_PASSWORD
};

#endif // DIALOGTYPEENUM_HPP
