#ifndef DIALOGRESULTENUM_HPP
#define DIALOGRESULTENUM_HPP

enum DialogResult{
    ACCEPT_RESULT,
    CANCEL_RESULT,
    YES_RESULT,
    NO_RESULT,
    FIRST_OPTION_RESULT,
    SECOND_OPTION_RESULT,
    THIRD_OPTION_RESULT
};

#endif // DIALOGRESULTENUM_HPP
