#ifndef DATABASESEARCHENGINEENUMS_HPP
#define DATABASESEARCHENGINEENUMS_HPP

enum DataBaseSearchEngineInitializerError{
    DATABASE_SEARCH_ENGINE_INITIALIZER_NO_ERROR,
    DATABASE_SEARCH_ENGINE_INITIALIZER_ERROR_DATABASE_UNINITIALIZED,
    DATABASE_SEARCH_ENGINE_INITIALIZER_ERROR_UNINITIALIZED,
    DATABASE_SEARCH_ENGINE_INITIALIZER_ERROR_CLEAR,
    NUMB_OF_DATABASE_SEARCH_ENGINE_INITIALIZER_ERRORS
};
enum DataBaseSearchEngineResultError{
    DATABASE_SEARCH_ENGINE_RESULT_NO_ERROR,
    DATABASE_SEARCH_ENGINE_RESULT_ERROR_INITIALIZED_BUT_NOT_EXECUTED,
    NUMB_OF_DATABASE_SEARCH_ENGINE_RESULT_ERRORS
};

#endif // DATABASESEARCHENGINEENUMS_HPP
