#ifndef DATABASESEARCHENGINEFILTERERROR_HPP
#define DATABASESEARCHENGINEFILTERERROR_HPP

enum DataBaseSearchEngineFilterError{
    DATABASE_SEARCH_ENGINE_FILTER_NO_ERROR,
    DATABASE_SEARCH_ENGINE_FILTER_ERROR_UNITIALIZED,
    NUMB_OF_DATABASE_SEARCH_ENGINE_FILTER_ERRORS
};

#endif // DATABASESEARCHENGINEFILTERERROR_HPP
