#ifndef LEDMATRIXPICTUREDATABASETYPES_HPP
#define LEDMATRIXPICTUREDATABASETYPES_HPP

enum FuzzyLogicRobotSimulationDataBaseTypes{
    FLRS_NO_TYPE,
    FLRS_SIMULATION_AREA_TEMPLATE,
    FLRS_SIMULATION_AREA_TEMPLATE_ELEMENT,
    NUMB_OF_FUZZY_LOGIC_ROBOT_SIMULATION_DATA_BASE_TYPES
};

#endif // LEDMATRIXPICTUREDATABASETYPES_HPP
