#ifndef PROGRAMCONTROLMENEGMENT_HPP
#define PROGRAMCONTROLMENEGMENT_HPP

#define INFINITE_LOOP while(true)
#define LOOP_VARIABLE_CONDITIONAL(varCond) while(varCond)

#endif // PROGRAMCONTROLMENEGMENT
