#ifndef LEDMATRIXPICTUREELEMENTTYPES_HPP
#define LEDMATRIXPICTUREELEMENTTYPES_HPP

enum SimulationAreaTemplateElementTypes{
    SIMULATION_AREA_TEMPLATE_ELEMENT_NO_TYPE, // ERROR
    SIMULATION_AREA_TEMPLATE_ELEMENT_TYPE_OBSTACLE,
    SIMULATION_AREA_TEMPLATE_ELEMENT_TYPE_SIMULATION_AREA,
    SIMULATION_AREA_TEMPLATE_ELEMENT_TYPE_ROBOT,
    NUMB_OF_SIMULATION_AREA_TEMPLATE_ELEMENT_TYPES
};

#endif // LEDMATRIXPICTUREELEMENTTYPES_HPP
