#ifndef LEDMATRIXPICTUREMODE_HPP
#define LEDMATRIXPICTUREMODE_HPP

#include<QObject>

class SimulationAreaTemplateElement;

enum SimulationAreaTemplateModeType{
    SIMULATION_AREA_TEMPLATE_MODE_DEFAULT,
    SIMULATION_AREA_TEMPLATE_MODE_ADD_ROBOT,
    SIMULATION_AREA_TEMPLATE_MODE_DRAW_RECT,
    SIMULATION_AREA_TEMPLATE_MODE_DRAW_ELIPSE,
    SIMULATION_AREA_TEMPLATE_MODE_ADD_SIMULATION_AREA,
    NUMB_OF_SIMULATION_AREA_TEMPLATE_MODE_TYPES
};

enum SimulationAreaTemplateModeDrawRectPhase{
    SIMULATION_AREA_TEMPLATE_MODE_DRAW_RECT_PHASE_START_POINT,
    SIMULATION_AREA_TEMPLATE_MODE_DRAW_RECT_PHASE_END_POINT
};

struct SimulationAreaTemplateMode{
    SimulationAreaTemplateModeType type = NUMB_OF_SIMULATION_AREA_TEMPLATE_MODE_TYPES;
    uint phase = 0;
    SimulationAreaTemplateElement* tempElement = nullptr;
};


#endif // LEDMATRIXPICTUREMODE_HPP
